### ISSUE TITLE
home work #1/1

### ISSUE THREAD

**Issue by radikzoom** [radikzoom/fuel-consumption#1]
@coursar дз на проверку
Загидуллин Радик 
1 группа Java

**Comment by coursar** [comment]
Пофиксить открытые issue. Не забывайте добавлять меня в collaborators

**Comment by radikzoom** [comment]
> Пофиксить открытые issue. Не забывайте добавлять меня в collaborators

Забыл про collaborators. 
Пофиксить открытые issue - недопонял :(
