### ISSUE TITLE
Всегда ли int?

### ISSUE THREAD

**Issue by coursar** [radikzoom/fuel-consumption#2]
https://github.com/radikzoom/FuelConsumption/blob/836f3afdf414435ef97592b08394a5b3cd4f9484/src/MainR.java#L4

**Comment by radikzoom** [comment]
`https://github.com/radikzoom/FuelConsumption/blob/bba8c527a3dd1e95565ee2081d0f99a913187bfe/src/MainR.java#L4
Можем целочисленные тип заменить на значение с плавыющей точкой float & double

**Comment by coursar** [comment]
Если сделали issue - закрывайте
